### ISSUE TITLE
logging errors in 2.2.0

### ISSUE THREAD

**Issue by bcoe** [jakerella/jquery-mockjax#298]
`jquery-mockajax@2.2.0` does not respsect `$.mockjaxSettings.logging = false`.

``` sh
/Users/benjamincoe/npm-inc/annotation-poller/node_modules/jquery-mockjax/src/jquery.mockjax.js:851
        logger:             window.console,
                                  ^

TypeError: Cannot read property 'console' of undefined
    at /Users/benjamincoe/npm-inc/annotation-poller/node_modules/jquery-mockjax/src/jquery.mockjax.js:851:20
    at Object.<anonymous> (/Users/benjamincoe/npm-inc/annotation-poller/test.js:9:484)
    at Module._compile (module.js:425:26)
```

**Comment by jakerella** [comment]
Hmm... are you using Mockjax in a Node context? If so, then there wouldn't be a `window` object, hence the error you're seeing. In my tests the `logging` option is working, but I did not test it when using Mockjax as a Node module. That should be an easy fix, at least, for the line you're referencing.

Can you change [line 851](https://github.com/jakerella/jquery-mockjax/blob/master/src/jquery.mockjax.js#L851) in your `node_modules/jquery-mockjax/src/jquery.mockjax.js` file to be:

`logger: console || null,`

**Comment by bcoe** [comment]
@jakerella I am using it for tests in a Node context:

https://github.com/npm/annotation-poller/blob/master/test.js#L23

**Comment by jakerella** [comment]
Aaah... yes, so you are not providing a global context, which is a requirement for Mockjax, on [line 11](https://github.com/npm/annotation-poller/blob/master/test.js#L11) of your test. That means that on line 851 of the source code `window` is undefined. You'll need to provide a global context somehow. You can check out our Node tests for the library to see how:

https://github.com/jakerella/jquery-mockjax/blob/master/test/nodejs/test.js

**Comment by bcoe** [comment]
@jakerella this was the approach I was using:

```js
require('jquery-mockjax')($)
$.mockjaxSettings.logging = false
```

which was working on `npm i jquery-mockjax@2.1.0`, what would the equivalent be in `2.2.0`?

**Comment by jakerella** [comment]
The problem is that the logger is now set in `$.mockjax.settings` when the file is required in Node. This worked for you in `2.1.0`, but you weren't actually using the library correctly as the second argument is not optional. You could try the code below, but you should really be providing a valid global context, something like what we have in the [Node tests](https://github.com/jakerella/jquery-mockjax/blob/master/test/nodejs/test.js) for this library.

So, the short answer is: implement what you see in [our tests](https://github.com/jakerella/jquery-mockjax/blob/master/test/nodejs/test.js). The alternative is try to an unsupported workaround like this:

`require('jquery-mockjax')($, global);`

That said, I don't even know if that would work since the Node `console` doesn't have an `info` method. I suppose you could just try this as well (again, a workaround, and not supported): 

`require('jquery-mockjax')($, {});`

**Comment by jakerella** [comment]
Closing for inactivity, please open a new issue if you still have questions or problems!
